OSU_PLAYFIELD_WIDTH = 512
OSU_PLAYFIELD_HEIGHT = 384
OSU_PLAYFIELD_RATIO = OSU_PLAYFIELD_WIDTH / OSU_PLAYFIELD_HEIGHT

MULTIPLER = 2

PLAYFIELD_MARGIN_LEFT = 160 * MULTIPLER
PLAYFIELD_MARGIN_RIGHT = 160 * MULTIPLER
PLAYFIELD_MARGIN_TOP = 90 * MULTIPLER
PLAYFIELD_MARGIN_BOTTOM = 90 * MULTIPLER