OSU_PLAYFIELD_WIDTH = 512
OSU_PLAYFIELD_HEIGHT = 384
OSU_PLAYFIELD_RATIO = OSU_PLAYFIELD_WIDTH / OSU_PLAYFIELD_HEIGHT

PLAYFIELD_MARGIN_LEFT = 300
PLAYFIELD_MARGIN_RIGHT = 300
PLAYFIELD_MARGIN_TOP = 100
PLAYFIELD_MARGIN_BOTTOM = 350